### ISSUE TITLE
Taak: Ontwerp voor opvang maken

### ISSUE THREAD

**Issue by cam-emmauscollege** [emmaus-6v/2122-6V-Knikkerbaan-groep-2#2]
**Korte beschrijving van je taak**:
Beslissen of de knikkerbaan in de breedte of in de hoogte ontworpen wordt.
Ontwerp maken van hoe de knikkers over een breedte van 10 centimeter kunnen worden opgevangen. Bedenken waar / hoe de teller wordt gemonteerd en waar de servo van het poortje zit.
Zorg ervoor dat er voor het poortje zeker zo'n 20 knikkers kunnen wachten.

**Geschatte tijdsduur:** 30 minuten

_overige informatie:_
de teller werkt met een infrarood ledje en ontvanger: https://www.kiwi-electronics.nl/nl/infrarood-straal-detector-3mm-leds-1576
de servo heeft een armpje, maar kan ook iets anders erop gemonteerd krijgen: https://www.kiwi-electronics.nl/nl/df9gms-360-micro-servo-1-6kg-cm-3749

**Comment by Jimmychao49** [comment]
- Hij wordt in de hoogte ontworpen 
- teller staat in het begin
- sensors bij de afsplitsing voor leds
- wordt afgesplitst naar trechter en rad en conjoinen daaronder
- onder de trechter en rad een teller
- onder het rad een poortje (sluit als er beweging langs teller trechter komt)
- schermpje om de snelheid te laten zien
